
[project]
name = "asura"
version = "0.1.0"
description = "A simple ML toolkit"
authors = [{ name = "Ait-Ameur Mohamed Ilyas" }]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
